[project]
name = "pynani"
version = "1.4.2"
description = "Open source python wrapper to Messenger API"
authors = [
  {name = "Jorge Juárez", email = "jorgeang33@gmail.com"},
]
keywords = ["Messenger", "wrapper", "Meta", "API", "Facebook", "Pynani"]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
  "Intended Audience :: Developers",
  "Intended Audience :: Customer Service",
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: MIT License",
  "Topic :: Communications :: Chat",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.12, <4.0"

dependencies = [
    "colorlog>=6.10.1",
    "requests>=2.33.1",
]

[dependency-groups]
docs = [
    "sphinx>=9.1.0",
    "sphinx-book-theme>=1.2.0",
    "sphinx-copybutton>=0.5.2",
]

[project.urls]
"Bug Tracker" = "https://github.com/jorge-jrzz/pynani/issues"
Repository = "https://github.com/jorge-jrzz/pynani"
Documentation = "https://pynani-docs.readthedocs.io/en/latest/"

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"
